### ISSUE TITLE
Correction to DEPLOY Page

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_cloud_threefold.io#35]
justin will edit this.

**Comment by js-threefold** [comment]
EDITS (using the attached screenshots): 

1 - Deploy
- ThreeFold logo goes over the node graphic and looks a little unclear. Please move logo to the right so it's all in the grey

<img width="571" alt="1 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358735-c88f0b80-cd35-11ea-9b9e-6145dcebbda0.png">

2 - Deploy
- Phone graphic at the left is cut off by lower section. Please make graphic display behind both sections so it runs all the way to the left edge

<img width="715" alt="2 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358737-c927a200-cd35-11ea-80e8-bff96469071a.png">

3 - Deploy
- Text needs to be aligned and not split on between "enjpy" and "compute". Additionally, text needs to be edited to read "Ensure the correct execution of your workloads and enjoy compute, network and web all in one place." 

<img width="835" alt="3 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358731-c7f67500-cd35-11ea-8e56-c37d47b4b227.png">

4 - Deploy 
- Change text under Peer 2 Peer Network to read: "Independent farmers dedicate hardware to form the ThreeFold Grid"

<img width="1571" alt="4 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358729-c6c54800-cd35-11ea-8e92-83f328beab4c.png">

5 - Deploy
- Change "lorem ispum" text to read: "Download and install the 3bot application to move your workload over today." 
- Step 4: Change "Chose" to "Choose"
- Step 5: Change "Get Off" to "Launch" 
- It looks like the grey background is a different color than used in the graphics — see the Step 1 and Step 2 images, the shadow under the elements does not match. Please change background to white to match the graphics and add shading to the boxes to set apart.

<img width="1444" alt="5 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358728-c62cb180-cd35-11ea-9189-63a5c584cb52.png">

6 - Deploy
- Change text below Pricing to: "The Grid is currently open for testing. During this phase you will be able to access capacity for free. After the testing phase, the reservation of capacity will be made through TFT and the pricing will be highly competitive." 
- Increase the font size of the pricing table below to better fit the space provided. The rows and columns should be aligned. 

<img width="1680" alt="6 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358727-c5941b00-cd35-11ea-8eac-ae8ec4094e75.png">

7 - Deploy
- Change text below "Planet Friendly" to: The ThreeFold architecture maximizes energy efficiency by leaving out unnecessary plumbing and utilizing green technology"
- Adjust the line spacing of this statement to single instead of double
- Increase the size of the graphic below 20-25% to fill more of the space left/right to the edge

<img width="1680" alt="7 - Deploy" src="https://user-images.githubusercontent.com/68718676/88358726-c3ca5780-cd35-11ea-865d-314e2ea2fb16.png">

OTHER EDITS: 

- Add site footer to bottom of the deploy page

<img width="1655" alt="Screenshot 2020-07-24 05 11 45" src="https://user-images.githubusercontent.com/68718676/88359874-e3fc1580-cd39-11ea-82c5-fe2632543a23.png">

**Comment by ehab-hassan** [comment]
All done waiting for verification

**Comment by js-threefold** [comment]
Remaining edits: 

Deploy main button on header needs to link to: https://sdk.threefold.io/#/gettingstarted

Subtext under heading "DECENTRALIZE YOUR APPLICATION" needs to be same as header subtext 1.5em

Subtext under heading "PLANET FRIENDLY" needs to be the same as header subtext 1.5em

Text for the DECENTRALIZE YOUR APPLICATION individual steps 1-5 need to match the text on https://cloud.threefold.io/

1. INSTALL the 3bot application
2. GET TFT For a limited amount of time only,
you can apply here to get Free TFT 
for testing purposes.
3. GET ACCESS to the ThreeFold manual.
4. CHOOSE
Exploration Mode - Explore and deploy workloads through a chat wizard.
Geek Mode - Code with building blocks that we provide.
Jumpscale Mode - Code directly into our blockchain database.
5. LIFT OFF as simple as that.

**Comment by js-threefold** [comment]
Remaining edits updated.

**Comment by js-threefold** [comment]
Last edit and can be closed — please hide this row of the table that shows 168 in four boxes: 

<img width="1140" alt="Screenshot 2020-07-28 at 13 32 56" src="https://user-images.githubusercontent.com/68718676/88660516-7f73ea00-d09c-11ea-8118-4819c9c03869.png">

**Comment by ehab-hassan** [comment]
done
