### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#50]
- [x] HOME "Decentralized storage and capacity with the

reliability and security of Blockchain."

-> Decentralized storage and compute for everyone, owned by everyone, everywhere.

- [x] TOKEN Estimated Grid Value -> In Hardware

**Comment by scottyeager** [comment]
My suggestion: "Decentralized storage and compute for everyone and owned by everyone, everywhere."

**Comment by BenjellounO** [comment]
My suggestion for the title: " The largest P2P cloud on the planet"

**Comment by samtaggart** [comment]
For @maximilianrang review before implementation:

**HOME**
- [x] "Grid On the Planet" should be moved up to the same line as the rest of the text in the header
- [x] "reliability and security of the blockchain" should be moved up to the same level as the rest of the text in the header
- [x] In general, we need consistency on if we are using "." or not at the end of titles and subtitles – too much irregularity
- [x] In general, decide between "internet" and "Internet"

Our operating system Zero-OS makes computers very trustworthy. We call these computers 3Nodes. These 3Nodes are what form the ThreeFold network, the world's largest peer-to-peer grid.
- [x] Our open source operating system, Zero-OS, makes computers very trustworthy. We call these computers 3Nodes. These 3Nodes are what form the ThreeFold Grid, the world's largest peer-to-peer network.

3Nodes form a global of decentralized storage and compute.
- [x] 3Nodes form a global network of decentralized storage and compute.

- [x] In the same paragraph, link to wiki section on Smart Contract for IT

This combined provides similar security and reliability as a Blockchain, but at the performance of high-end server technology.
- [x] These two factors combined provide similar security and reliability as a Blockchain, but with the performance of high-end server technology.

Any application which can run on linux
- [x] Any application which can run on Linux

AI and VR/Ar,
- [x] AI, VR, and AR,

Any application that runs on Kubernetes, Docker or
even Linux can be deployed on the ThreeFold Grid.
- [x] has unnecessary line breaks

**FARMING**
- [x] Once again, need to decide about "." in titles and subtitles
- [x] Once again, need to decide about "internet" or "Internet"

The ThreeFold Grid is currently distributed across 21+ countries
- [x] I think we're only at 16 for now

TEN THOUSAND MORE 3NODES IN 2020
- [x] 10,000 MORE 3NODES IN 2020 – would be more consistent

twenty thousand CPU cores live
- [x] 20,000 CPU cores live – would be more consistent

is BIOS locked
- [x] what is BIOS? should spell it out

privacy & security, sustainability.
- [x] privacy & security, and sustainability

Algorythms ensure that all data is hosted where it is needed in order to reduce redunduncy.
- [x] Algorithms ensure that all data is hosted where it is needed in order to reduce redundancy.

A stirage algorithm inspired by space-technology
- [x] A storage algorithm inspired by space technology

Being decentralized and using
- [x] Because it is decentralized and uses
- [x] Should we link to the energy saving blog article in the same paragraph where it says "90%"

algorithms prove that workdloads
- [x] Algorithms prove that workloads

**ABOUT US**
- [x] Once again, need to decide about "." in titles and subtitles
- [x] Once again, need to decide about "internet" or "Internet"

We grow a sustainable
- [x] We are collectively growing

become the ThreeFold movement
- [x] become the ThreeFold Movement

**PARTNERS**
- [x] Once again, need to decide about "." in titles and subtitles
- [x] Once again, need to decide about "internet" or "Internet"

Are projects that empower a decentralised
- [ ] Are projects that empower a decentralized
- [ ] "decentralised" also appears in the next sentence

Are platforms where people and organisations
- [x] organizations

**IN THE NEWS**
- [x] Once again, need to decide about "internet" or "Internet"
- [x] Remove "." from Hackernoon article
- [x] Citiesabc article - Threefold --> ThreeFold
- [x] Selfkey --> SelfKey
- [x] Hackernoon --> Hacker Noon
- [x] Citiesabc --> citiesabc

**DEPLOY**
- [x] Once again, need to decide about "." in titles and subtitles
- [x] Once again, need to decide about "internet" or "Internet"
- [x] Remove line breaks in title and subtitle

Utilize capacity in 21+ countries
- [x] 21+ or 16?

- [x] 3bot --> 3Bot (multiple)
- [x] 3Bot or 3Bot Connect ?

To the ThreeFold manual
- [x] to the ThreeFold manual

the 3bot application
- [x] the 3Bot (Connect) application.

workloadsthrough
- [x] workloads through

as simple as that.
- [x] As simple as that.

The Grid is currently open
- [x] The ThreeFold Grid or The grid

**TOKEN**
- [x] Once again, need to decide about "." in titles and subtitles
- [x] Once again, need to decide about "internet" or "Internet"

and can be exchanged for the capacity at any time.
- [x] and can be exchanged for capacity at any time.

There is no centerlized issuance.
- [x] There is no centralized issuance.

**Comment by samtaggart** [comment]
> My suggestion: "Decentralized storage and compute for everyone and owned by everyone, everywhere."

I agree with this, compared to what we have now: Decentralized storage and capacity with the
reliability and security of Blockchain.
